spring.application.name=ClickAgenda

# DataSource
spring.datasource.url=jdbc:h2:file:./db/clickagenda
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update

# Mantém as tabelas entre inicializações
spring.jpa.hibernate.ddl-auto=update

# JWT Configuration
jwt.secret=ClickAgenda@SecureKeyForJWT2024!ChangeInProduction#MustBeVeryLongAndSecure
jwt.expiration=86400000

# Error Handling
spring.web.error.whitelabel.enabled=false
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
spring.web.error.include-stacktrace=on_param
spring.web.error.include-exception=false